Direct syscalls implementation
rapid7/ReflectiveDLLInjection pull request #15
Opened 2023-10-04 20:14 UTC by cdelafuente-r7

This PR brings direct syscalls capability to the original Reflective DLL Injection library. This includes the logic to retrieve the syscall numbers using a new technique based on [RecycledGate](https://github.com/thefLink/RecycledGate). This technique uses the same trampoline logic to ensure that all system calls go through `ntdll.dll`. However, the original code that retrieves the syscall numbers when the dll is hooked by an EDR has been replaced by another technique that involves creating a process in a suspend state, called [Freeze](https://github.com/optiv/Freeze). As a result, I shamelessly called this new technique **ColdGate**.

The original technique, which comes from [Halo's Gate](https://blog.sektor7.net/#!res/2021/halosgate.md) implementation, consists in looking at the adjacent syscalls implementation in the loaded `ntdll.dll` until a non-hooked syscall is found and deducing the original syscall number. This has a strong assumption that syscalls numbers are sequential, which is not always the case. The Freeze technique behaves differently. It first creates a process in a suspend state, which automatically loads `ntdll.dll` in memory. The dll is not yet hooked by any EDR since no thread has been started. So, it copies the dll's `.text` section from the new process to a local memory location and starts looking at syscalls numbers, which are not hooked. More info about this technique can be found [here](https://www.optiv.com/insights/source-zero/blog/sacrificing-suspended-processes).

A few native API functions have been implemented with these techniques so far:
- NtAllocateVirtualMemory
- NtProtectVirtualMemory
- NtFlushInstructionCache
- NtLockVirtualMemory
- NtReadVirtualMemory
- NtClose
- NtTerminateProcess
- NtFreeVirtualMemory

These functions now replace the functions used by the original Reflective DLL Injection implementation.

This also supports x86, x64 and Wow64 architectures. Note that ARM is not supported.

This PR is still a WIP since a lot of testing needs to be done to make sure it works on all the Windows flavors. So far, this has been tested successfully on the following systems:
- Windows 11 x64
- Windows 10 x64
- Windows 7 x64 and x86
- Windows Server 2019 x64
- Windows Server 2016 x64
- Windows Server 2012 x64
- Windows Server 2008 R2 x64

## Testing
This has been compiled using the standard platform toolset of Visual Studio 2019 (v142). This might still work with other versions but it has not been tested.

You will need to open the solution with Visual Studio, select the `Release` configuration (`Debug` doesn't work for some reasons I haven't investigated yet) and select the platform `x64` or `Win32`, according to your target OS. Note that Wow64 binaries are supported, so you can still run a x86 binary on a x64 architecture.

The build will generate an executable and a dll.
For a x86 build:
- `Release\inject.Win32.exe`
- `Release\reflective_dll.Win32.dll`

For a x64 build:
- `x64\Release\inject.x64.exe`
- `x64\Release\reflective_dll.x64.dll`

Note that both the executable and the dll need to be located in the same folder.

Executing the `inject` binary should inject the dll and pop up a Messagebox:

![Screenshot 2023-10-04 at 22 06 00](https://github.com/rapid7/ReflectiveDLLInjection/assets/56716719/52fe91d9-3cb4-48f5-a967-a20939dbd634)

## TODO
1. Add a custom implementation of the following functions from `kernel32.dll`:
- LoadLibraryA
- GetProcAddress
- GetSystemDirectoryA
- CreateProcessA

These functions are used by the reflective loader and during the unhooking process. Getting rid of calls through `kernel32.dll` would certainly reduce the footprint.

2. Integrate all of this with Meterpreter

2023-10-23 17:47 UTC, smcintyre-r7 requested changes

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +			break;
Looks like this is missing a `--dwCounter`.

```suggestion
			}
			--dwCounter;
			break;

```

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +		}
Alot of this looks like it could be condensed down.

```suggestion
		case NTTERMINATEPROCESS_HASH:
		    dwCryptedHash = NTTERMINATEPROCESS_HASH
		    --dwCounter;
		    break;
		...
		
		  dwUilitySyscallsIdx = NTTERMINATEPROCESS_SYSCALL
	if (dwIdxSyscall < dwSyscallSize && Syscalls[dwIdxSyscall].dwCryptedHash == dwCryptedHash) {
		UilitySyscalls[uilitySyscallsIdx] = Syscalls[dwIdxSyscall];
	}
	else {
		if (!ExtractSysCallData(pStub, &UilitySyscalls[uilitySyscallsIdx]))
			return FALSE;
	}

```

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +BOOL UnhookSyscalls(PVOID pNtdllBase, UtilityFunctions* pUtilityFunctions, Syscall Syscalls[], DWORD dwSyscallSize, Syscall UtilitySyscalls[], DWORD dwUilitySyscallSize) {
Since this isn't technically unhooking the syscalls by altering the current process's memory, this method might be more accurately named "GetHookedSyscallNumbers".

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +BOOL getSyscallsFromNtdll(PVOID pNtdllBase, Syscall Syscalls[], DWORD dwSyscallSize, Syscall UilitySyscalls[], DWORD dwUilitySyscallSize) {
UilitySyscalls I think is missing the T for UtilitySyscalls.

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/GateTrampolin32.asm
> +  lea eax, [4*eax]                 ; calculate the nukber of bytes needed to store the arguments
```suggestion
  lea eax, [4*eax]                 ; calculate the number of bytes needed to store the arguments

```

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +// If the correcponding syscall is hooked, the hooked function will be called directly. We cannot do anything about it.
```suggestion
// If the corresponding syscall is hooked, the hooked function will be called directly. We cannot do anything about it.

```

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +			// C3                           retn
Does this also cover Vista and Windows XP?

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +			break;
```suggestion
			return TRUE;
```

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +	*pNtdllBase = NULL;
Seems like either both pNtdllBase and pKernel32 should be set to NULL or neither should be set to NULL.

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +		return FALSE;
Since you're not allocating the buffer, why not just skip this part and let `GetSystemDirectoryA` handle the size check? You'll just need to make sure that `szPath` is null terminated, perhaps by decrementing `usPathSize` by one if necessary.

2023-10-23 17:47 UTC, smcintyre-r7 commented on dll/src/ColdGate.c
> +			// First, get the offset of the trampolin address.
```suggestion
			// Now, the trampoline address (pColdGate) points to an address located in the local copy of ntdll.
			// We need to set it to a trampoline address in the loaded ntdll.
			// First, get the offset of the trampoline address.
```

2023-11-09 16:05 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +			break;
Good catch! Addressed in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 16:56 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +		}
I like this one, thanks for the suggestion!

Addressed in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 16:57 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +BOOL UnhookSyscalls(PVOID pNtdllBase, UtilityFunctions* pUtilityFunctions, Syscall Syscalls[], DWORD dwSyscallSize, Syscall UtilitySyscalls[], DWORD dwUilitySyscallSize) {
I agree, I changed this in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 16:57 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +BOOL getSyscallsFromNtdll(PVOID pNtdllBase, Syscall Syscalls[], DWORD dwSyscallSize, Syscall UilitySyscalls[], DWORD dwUilitySyscallSize) {
Good catch! Thanks!

Addressed in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 16:58 UTC, cdelafuente-r7 commented on dll/src/GateTrampolin32.asm
> +  lea eax, [4*eax]                 ; calculate the nukber of bytes needed to store the arguments
Addressed in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 16:58 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +// If the correcponding syscall is hooked, the hooked function will be called directly. We cannot do anything about it.
Addressed in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 16:59 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +			break;
Addressed in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 16:59 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +	*pNtdllBase = NULL;
Yes, you 're right.

Addressed in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 17:01 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +		return FALSE;
Yes, absolutely. I changed this in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 17:02 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +			// First, get the offset of the trampolin address.
Addressed in [0dd12e8](https://github.com/rapid7/ReflectiveDLLInjection/pull/15/commits/0dd12e8b0231f1a4d43027fba6eeefef8af57a16)

2023-11-09 17:39 UTC, cdelafuente-r7 commented on dll/src/ColdGate.c
> +			// C3                           retn
Yes, it covers Vista and XP x64. I updated the comment and also for the x86 section.

2023-11-15 20:22 UTC, smcintyre-r7 commented
I gave this a quick test on Windows 11 x64, and the results were all good. The changes built without any issues. Once I had it built, I used [API Monitor 2.0](http://www.rohitab.com/apimonitor) to track the NT calls you noted in the description. I then compared the output of the included `inject.x64.exe` binary to the one currently in the `master` branch to confirm that there are fewer API calls present because they have been replaced with syscalls.

I noticed the following reduction:
* NtAllocateVirtualMemory: 1 less
* NtProtectVirtualMemory: 6 less
* NtLockVirtualMemory: 1 less
* NtReadVirtualMemory: 0 less (was 5 to begin with)
* NtFlushInstructionCache: 0 less (was 0 to begin with)
* NtFreeVirtualMemory: 0 less (was 1 to being with)

2023-11-15 22:21 UTC, smcintyre-r7 commented on dll/src/ReflectiveLoader.c
> +#endif
These indexes are a little difficult to track while reading through the source code. The indexes also can't be constants because of how `ColdGate.c` uses it's own array of syscalls to define the ones it needs.

It would help to define them individually:

```suggestion
	// The NTDLL exported functions our loader needs. This array of Syscall structures will be completed later.
    Syscall NtAllocateVirtualMemorySyscall = { NTALLOCATEVIRTUALMEMORY_HASH, 6, FALSE };
    Syscall NtProtectVirtualMemorySyscall = { NTPROTECTVIRTUALMEMORY_HASH, 5, FALSE };
    Syscall NtFlushInstructionCacheSyscall = { NTFLUSHINSTRUCTIONCACHE_HASH, 3, FALSE };
#ifdef ENABLE_STOPPAGING
    Syscall NtLockVirtualMemorySyscall = { NTLOCKVIRTUALMEMORY_HASH, 4, FALSE };
#endif
```

Note that technically per the [C99](https://www.dii.uchile.cl/~daespino/files/Iso_C_1999_definition.pdf) spec, you could also omit the `FALSE` at the end if you want to favor brevity over verbosity.

This same suggestion goes for what is written in ColdGate as well.

2023-11-15 22:21 UTC, smcintyre-r7 commented on dll/src/ColdGate.h
> +NTSTATUS msfNtFreeVirtualMemory(Syscall * pSyscall, HANDLE hProcess, PVOID * pBaseAddress, PSIZE_T pRegionSize, ULONG uFreeType);
I'm really sorry to ask to change this but since these files aren't actually a part of Metasploit but rather a library that we rely on, it might make more sense to use a different prefix to denote where they are. `rdi` for reflective-dll-injection, might be a better option.

2023-12-04 17:25 UTC, cdelafuente-r7 commented on dll/src/ReflectiveLoader.c
> +#endif
Thanks for the suggestions, I addressed this in 10fe5f7ad6f28f68f257533e36f94018c4d68ab1

2023-12-04 17:25 UTC, cdelafuente-r7 commented on dll/src/ColdGate.h
> +NTSTATUS msfNtFreeVirtualMemory(Syscall * pSyscall, HANDLE hProcess, PVOID * pBaseAddress, PSIZE_T pRegionSize, ULONG uFreeType);
No worry, I also agree the `rdi` prefix makes more sense. Addressed in 10fe5f7ad6f28f68f257533e36f94018c4d68ab1.

2024-01-08 17:40 UTC, cdelafuente-r7 commented
Closing this PR since a new PR with an updated implementation exists [here](https://github.com/rapid7/ReflectiveDLLInjection/pull/16)

2024-01-08 17:40 UTC, closed without merging